/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    journeys: Journey;
    pages: Page;
    users: User;
    otpChallenges: OtpChallenge;
    sessions: Session;
    signInAttempts: SignInAttempt;
    jobs: Job;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    journeys: JourneysSelect<false> | JourneysSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    otpChallenges: OtpChallengesSelect<false> | OtpChallengesSelect<true>;
    sessions: SessionsSelect<false> | SessionsSelect<true>;
    signInAttempts: SignInAttemptsSelect<false> | SignInAttemptsSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    book: Book;
    about: About;
    site: Site;
  };
  globalsSelect: {
    book: BookSelect<false> | BookSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    site: SiteSelect<false> | SiteSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  journey?: (number | null) | Journey;
  kind?: ('still' | 'clip') | null;
  caption?: string | null;
  alt?: string | null;
  capturedAt?: string | null;
  posterAt?: number | null;
  posterImage?: (number | null) | Media;
  durationSec?: number | null;
  inBook?: boolean | null;
  hidden?: boolean | null;
  isCover?: boolean | null;
  allowDownload?: boolean | null;
  order?: number | null;
  contentHash?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tile?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    frame?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero2x?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journeys".
 */
export interface Journey {
  id: number;
  name: string;
  place: string;
  slug: string;
  dates: string;
  startsOn?: string | null;
  order?: number | null;
  hiddenFromBookmarks?: boolean | null;
  archived?: boolean | null;
  deletedAt?: string | null;
  weather?: string | null;
  mood?: string | null;
  weatherGlyph?: ('sun' | 'haze' | 'wind') | null;
  furniture?: {
    signoff?: string | null;
    stampCountry?: string | null;
    stampValue?: string | null;
    accent?: string | null;
  };
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  note?: string | null;
  tally?:
    | {
        key?: string | null;
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  journey: number | Journey;
  kind: 'notes' | 'frames';
  title?: string | null;
  order: number;
  layout?: ('three-up' | 'four-up' | 'full-bleed' | 'text-spread') | null;
  slots?:
    | {
        role?: ('hero' | 'ephemera' | 'frame') | null;
        media?: (number | null) | Media;
        caption?: string | null;
        alt?: string | null;
        focalX?: number | null;
        focalY?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  displayName?: string | null;
  signoffDefault?: string | null;
  timeZone?: string | null;
  otpRequired?: boolean | null;
  notifyOnPublish?: boolean | null;
  notifyWeekly?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "otpChallenges".
 */
export interface OtpChallenge {
  id: number;
  user: number | User;
  codeHash: string;
  sessionHash: string;
  expiresAt: string;
  attempts?: number | null;
  consumedAt?: string | null;
  ip?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions".
 */
export interface Session {
  id: number;
  user: number | User;
  tokenHash: string;
  expiresAt: string;
  device?: string | null;
  location?: string | null;
  lastSeenAt?: string | null;
  revokedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "signInAttempts".
 */
export interface SignInAttempt {
  id: number;
  dimension: 'ip' | 'account';
  endpoint: 'password' | 'code';
  subject: string;
  attemptedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  kind: 'transcode';
  mediaId: string;
  status: 'queued' | 'claimed' | 'completed' | 'failed';
  reason?: string | null;
  claimedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'journeys';
        value: number | Journey;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'otpChallenges';
        value: number | OtpChallenge;
      } | null)
    | ({
        relationTo: 'sessions';
        value: number | Session;
      } | null)
    | ({
        relationTo: 'signInAttempts';
        value: number | SignInAttempt;
      } | null)
    | ({
        relationTo: 'jobs';
        value: number | Job;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  journey?: T;
  kind?: T;
  caption?: T;
  alt?: T;
  capturedAt?: T;
  posterAt?: T;
  posterImage?: T;
  durationSec?: T;
  inBook?: T;
  hidden?: T;
  isCover?: T;
  allowDownload?: T;
  order?: T;
  contentHash?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tile?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        frame?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero2x?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journeys_select".
 */
export interface JourneysSelect<T extends boolean = true> {
  name?: T;
  place?: T;
  slug?: T;
  dates?: T;
  startsOn?: T;
  order?: T;
  hiddenFromBookmarks?: T;
  archived?: T;
  deletedAt?: T;
  weather?: T;
  mood?: T;
  weatherGlyph?: T;
  furniture?:
    | T
    | {
        signoff?: T;
        stampCountry?: T;
        stampValue?: T;
        accent?: T;
      };
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  note?: T;
  tally?:
    | T
    | {
        key?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  journey?: T;
  kind?: T;
  title?: T;
  order?: T;
  layout?: T;
  slots?:
    | T
    | {
        role?: T;
        media?: T;
        caption?: T;
        alt?: T;
        focalX?: T;
        focalY?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  displayName?: T;
  signoffDefault?: T;
  timeZone?: T;
  otpRequired?: T;
  notifyOnPublish?: T;
  notifyWeekly?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "otpChallenges_select".
 */
export interface OtpChallengesSelect<T extends boolean = true> {
  user?: T;
  codeHash?: T;
  sessionHash?: T;
  expiresAt?: T;
  attempts?: T;
  consumedAt?: T;
  ip?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions_select".
 */
export interface SessionsSelect<T extends boolean = true> {
  user?: T;
  tokenHash?: T;
  expiresAt?: T;
  device?: T;
  location?: T;
  lastSeenAt?: T;
  revokedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "signInAttempts_select".
 */
export interface SignInAttemptsSelect<T extends boolean = true> {
  dimension?: T;
  endpoint?: T;
  subject?: T;
  attemptedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  kind?: T;
  mediaId?: T;
  status?: T;
  reason?: T;
  claimedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "book".
 */
export interface Book {
  id: number;
  title?: string | null;
  subtitle?: string | null;
  owner?: string | null;
  coverCloth?: string | null;
  yearsShown?: string | null;
  contentsNote?: string | null;
  flipDurationMs?: number | null;
  galleryThumbPx?: number | null;
  showDecorations?: boolean | null;
  showRibbon?: boolean | null;
  showCounter?: boolean | null;
  journeyOrderMode?: ('manual' | 'newest' | 'oldest') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  portrait?: (number | null) | Media;
  portraitCaption?: string | null;
  paragraphs?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  kit?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  replyTo?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site".
 */
export interface Site {
  id: number;
  name?: string | null;
  domain?: string | null;
  description?: string | null;
  replyTo?: string | null;
  analyticsId?: string | null;
  allowDownloads?: boolean | null;
  allowShare?: boolean | null;
  indexGalleries?: boolean | null;
  passwordProtect?: boolean | null;
  touchPageTurn?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "book_select".
 */
export interface BookSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  owner?: T;
  coverCloth?: T;
  yearsShown?: T;
  contentsNote?: T;
  flipDurationMs?: T;
  galleryThumbPx?: T;
  showDecorations?: T;
  showRibbon?: T;
  showCounter?: T;
  journeyOrderMode?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  portrait?: T;
  portraitCaption?: T;
  paragraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  kit?:
    | T
    | {
        text?: T;
        id?: T;
      };
  replyTo?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_select".
 */
export interface SiteSelect<T extends boolean = true> {
  name?: T;
  domain?: T;
  description?: T;
  replyTo?: T;
  analyticsId?: T;
  allowDownloads?: T;
  allowShare?: T;
  indexGalleries?: T;
  passwordProtect?: T;
  touchPageTurn?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}