/**
 * 20260910_171154_add_media_state — `media.state` and `media.failure_reason`.
 *
 * Generated by `payload migrate:create` from the two fields Phase 3 Task 5
 * added to `apps/web/collections/media.ts`, then hand-fixed. Implements no
 * §3.3 pattern and cannot: a migration is a pair of statement lists Payload
 * calls, and the shape is Payload's, not ours.
 *
 * TWO HAND-FIXES, both the recurring ones (docs/data-model.md): the
 * `MigrateUpArgs`/`MigrateDownArgs` import is type-only, because Payload emits
 * it without `type` and Node's built-in type-stripping cannot infer that, so
 * the file as generated fails to load under the Payload CLI; and the unused
 * `payload`/`req` parameters are underscore-prefixed for `noUnusedParameters`.
 *
 * TWO HAND-FIXES THIS ONE DID NOT NEED, checked rather than assumed. The
 * generator emitted `ADD COLUMN "state" ... DEFAULT 'processing'` with no
 * `NOT NULL`, so there is no add-nullable/backfill/`SET NOT NULL` split to
 * make (the split `20260906_004937_add_session_expiry` carries): this `up()`
 * already succeeds against a `media` table with rows. And its `down()`
 * already drops the two columns BEFORE `enum_media_state`, which is the order
 * the re-apply needs - a `DROP TYPE` before the column that uses it fails
 * outright, and a `down()` that dropped the columns and left the type behind
 * would fail its own `up()` with "type already exists".
 *
 * NO BACKFILL, deliberately. A row that predates this column reads `state`
 * NULL rather than being asserted into one of the three states: `processing`
 * would claim a pipeline run that is not happening - and spec §9.2 makes
 * `processing` a state the Media screen draws progress for, so it would be a
 * visible lie - while `ready` would claim five derivative tiers this migration
 * has not looked at. NULL says "ingested before there was a state to record",
 * which is the only true thing available. Only the seed writes `media` rows
 * today, and re-running it writes rows through the default.
 *
 * Depends on: `@payloadcms/db-postgres`'s `sql` tag and its migration arg types.
 */
import { sql } from '@payloadcms/db-postgres'
import type { MigrateDownArgs, MigrateUpArgs } from '@payloadcms/db-postgres'

/**
 * Adds the enum type, the state column and the failure-reason column.
 * @param args - Payload's migration arguments; only `db` is read.
 */
export async function up({ db, payload: _payload, req: _req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_media_state" AS ENUM('processing', 'ready', 'failed');
  ALTER TABLE "media" ADD COLUMN "state" "enum_media_state" DEFAULT 'processing';
  ALTER TABLE "media" ADD COLUMN "failure_reason" varchar;`)
}

/**
 * Drops both columns, then the enum type - in that order, see the header.
 * @param args - Payload's migration arguments; only `db` is read.
 */
export async function down({ db, payload: _payload, req: _req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "media" DROP COLUMN "state";
  ALTER TABLE "media" DROP COLUMN "failure_reason";
  DROP TYPE "public"."enum_media_state";`)
}
