/**
 * 20260913_201520_add_media_grid_tier — the six columns one `imageSize` adds.
 *
 * Generated by `payload migrate:create` from the `grid` tier Phase 3 Task 10
 * added to `apps/web/collections/media.ts` (ADR 0013 Option 3, deferred to
 * this phase by that ADR). Implements no §3.3 pattern and cannot: a migration
 * is a pair of statement lists Payload calls, and the shape is Payload's.
 *
 * ONE `imageSize` IS SEVEN ARTEFACTS, not one. Payload derives a column per
 * size FIELD - `url`, `width`, `height`, `mime_type`, `filesize`, `filename` -
 * plus a btree index on the filename it looks a derivative up by. That is why
 * `collections.integration.test.ts`'s reversibility case asserts on all seven:
 * a `down()` that dropped `sizes_grid_url` alone would leave five orphan
 * columns its own `up()` could not re-add.
 *
 * THE TWO RECURRING HAND-FIXES (docs/data-model.md): the
 * `MigrateUpArgs`/`MigrateDownArgs` import is type-only, because Payload emits
 * it without `type` and Node's built-in type-stripping cannot infer that, so
 * the file as generated fails to load under the Payload CLI; and the unused
 * `payload`/`req` parameters are underscore-prefixed for `noUnusedParameters`.
 *
 * A HAND-FIX THIS ONE DID NOT NEED, checked rather than assumed. The
 * generated `down()` already drops the INDEX before the column it is built
 * on, which is the order a re-apply needs - and the reverse would in fact
 * still work here, since Postgres drops an index with its column, so this is
 * the rarer case of the generator's order being merely correct rather than
 * load-bearing. Every statement is an `ALTER TABLE ... ADD COLUMN` with no
 * `NOT NULL` and no default, so `up()` succeeds against a `media` table full
 * of rows.
 *
 * NO BACKFILL, AND NO BACKFILL IS POSSIBLE HERE. The six columns describe a
 * FILE that does not exist yet: a derivative has to be generated from the
 * original before there is a filename to record. `apps/web/scripts/rederive-
 * media.ts` (`npm run media:rederive`) is what fills them, by re-uploading
 * each row's own original through Payload so Payload re-runs its derivative
 * generation - see docs/runbook.md. A row whose columns are still NULL reads
 * as a row the re-derivation has not reached, which is the only true thing
 * this migration can say about it.
 *
 * Depends on: `@payloadcms/db-postgres`'s `sql` tag and its migration arg types.
 */
import { sql } from '@payloadcms/db-postgres'
import type { MigrateDownArgs, MigrateUpArgs } from '@payloadcms/db-postgres'

/**
 * Adds the six `sizes_grid_*` columns and the filename index.
 * @param args - Payload's migration arguments; only `db` is read.
 */
export async function up({ db, payload: _payload, req: _req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "media" ADD COLUMN "sizes_grid_url" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_grid_width" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_grid_height" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_grid_mime_type" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_grid_filesize" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_grid_filename" varchar;
  CREATE INDEX "media_sizes_grid_sizes_grid_filename_idx" ON "media" USING btree ("sizes_grid_filename");`)
}

/**
 * Drops the index, then all six columns - see the header for the order.
 * @param args - Payload's migration arguments; only `db` is read.
 */
export async function down({ db, payload: _payload, req: _req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   DROP INDEX "media_sizes_grid_sizes_grid_filename_idx";
  ALTER TABLE "media" DROP COLUMN "sizes_grid_url";
  ALTER TABLE "media" DROP COLUMN "sizes_grid_width";
  ALTER TABLE "media" DROP COLUMN "sizes_grid_height";
  ALTER TABLE "media" DROP COLUMN "sizes_grid_mime_type";
  ALTER TABLE "media" DROP COLUMN "sizes_grid_filesize";
  ALTER TABLE "media" DROP COLUMN "sizes_grid_filename";`)
}
