/**
 * 20261004_085050_add_reader_password — the one column a reader password needs.
 *
 * Generated by `payload migrate:create` from the `readerPasswordHash` field
 * added to `apps/web/globals/site.ts`. Implements no §3.3 pattern and cannot:
 * a migration is a pair of statement lists Payload calls, and the shape is
 * Payload's.
 *
 * WHAT THE COLUMN HOLDS IS NEVER A PASSWORD. It holds
 * `scrypt$<salt hex>$<key hex>`, written only by `setReaderPassword` in
 * `apps/web/lib/admin/siteMutations.ts`. `docs/deviations.md` §100 records
 * why the column did not exist before: the book could be closed but never
 * opened, because there was nothing to check a reader against.
 *
 * THE TWO RECURRING HAND-FIXES (`docs/data-model.md`): the
 * `MigrateUpArgs`/`MigrateDownArgs` import is type-only, because Payload emits
 * it without `type` and Node's built-in type-stripping cannot infer that, so
 * the file as generated fails to load under the Payload CLI; and the unused
 * `payload`/`req` parameters are underscore-prefixed for `noUnusedParameters`.
 *
 * NO BACKFILL, AND NONE IS POSSIBLE. A hash cannot be derived from a password
 * nobody has typed. A `site` row whose column is still NULL reads as a diary
 * with no reader password set — which is every diary until an author types
 * one, and which `setReaderSetting` refuses to close the book over.
 *
 * REVERSIBLE WITHOUT LOSS OF ANYTHING BUT THE HASH, deliberately: `down()`
 * drops the column, and an author who re-applies this migration types their
 * password again. There is nothing else to restore, and a backup of a
 * password hash is a thing worth not keeping.
 *
 * Depends on: `@payloadcms/db-postgres`'s `sql` tag and its migration arg types.
 */
import { sql } from '@payloadcms/db-postgres'
import type { MigrateDownArgs, MigrateUpArgs } from '@payloadcms/db-postgres'

/**
 * Adds `site.reader_password_hash`, nullable and with no default.
 * @param args - Payload's migration arguments; only `db` is read.
 */
export async function up({ db, payload: _payload, req: _req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "site" ADD COLUMN "reader_password_hash" varchar;`)
}

/**
 * Drops the column. See the header for why nothing else is undone.
 * @param args - Payload's migration arguments; only `db` is read.
 */
export async function down({ db, payload: _payload, req: _req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "site" DROP COLUMN "reader_password_hash";`)
}
